name: edgex-snap-hooks
base: core20
version: test
summary: EdgeX Snap Hooks package tester
description: This snap is used to run tests on this package

grade: devel
confinement: strict


apps:
  # App for running the tests
  test:
    command: snap/local/bin/test.sh
    plugs: [network, home]

  # Mocked apps needed for testing
  mock-service: &ms
    command: snap/local/bin/mock-app.sh
    daemon: simple
    install-mode: disable
  mock-service-2: *ms


parts:
  go:
    ## Using stage go snap doesn't work, 
    ## resulting in core dump when running go:
    # plugin: nil
    # stage-snaps: 
    #   - go/1.17
    # organize:
    #   '*': go/
    plugin: dump
    source: https://go.dev/dl/go1.17.6.linux-amd64.tar.gz
    organize:
      "*": go/

  # maintain test and binary files structure to simplify test development
  tests:
    plugin: dump
    source: .
