name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # allow running manually
  workflow_dispatch:

env:
  SNAPCRAFT_BUILD_ENVIRONMENT: lxd

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Install Snapcraft
      run: |
        sudo snap install snapcraft --classic
    - name: Setup LXD
      uses: whywaita/setup-lxd@v1
      with:
        lxd_version: latest/stable

    - name: Build and install the tester Snap
      run: |
        snapcraft
        sudo snap install ./edgex-snap-hooks_test_amd64.snap --dangerous

    - name: Run Tests
      run: |
        make test