name: Test

on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # this will install and run snapcraft internally
    - uses: snapcore/action-build@v1
      # with:
      #   snapcraft-args: prime
      #   build-info: false

    # - name: Unit Tests
    #   run: snapcraft prime unit-tests