name: Test

on:
#   push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]
  # allow running manually
  workflow_dispatch:

env:
  SNAPCRAFT_BUILD_ENVIRONMENT: lxd
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Snapcraft with LXD
      uses: samuelmeuli/action-snapcraft@v1
      with:
        use_lxd: true

    - name: Unit Tests
      run: snapcraft prime unit-tests