name: Test

on:
#   push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]
  # allow running manually
  workflow_dispatch:

env:
  SNAPCRAFT_BUILD_ENVIRONMENT: lxd

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Snapcraft with LXD
      run: |
        sudo snap install snapcraft --classic
    #     sudo snap install lxd
    #     sudo lxd init --auto

    - name: Setup LXD
      uses: whywaita/setup-lxd@v1
      with:
        lxd_version: latest/stable

    - name: Unit Tests
      run: snapcraft prime unit-tests