name: Test

on:
#   push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]
  # allow running manually
  workflow_dispatch:

env:
  SNAPCRAFT_BUILD_ENVIRONMENT: lxd

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install Snapcraft
      run: |
        sudo snap install snapcraft --classic

    - name: Setup LXD
      uses: whywaita/setup-lxd@v1
      with:
        lxd_version: latest/stable

    - name: Unit Tests
      run: snapcraft build unit-tests